version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: unless-stopped
    ports:
      - "9871:9870"   # Namenode Web UI
      - "8020:8020"   # HDFS service
    volumes:
      - namenode-data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: unless-stopped
    ports:
      - "9866:9866"  # DataNode IPC
      - "9864:9864"  # DataNode HTT
    depends_on:
      - namenode
    volumes:
      - datanode-data:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

volumes:
  namenode-data:
  datanode-data: