services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    command: sbin/start-master.sh -p 7077
    volumes:
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./scripts:/opt/bitnami/spark/scripts
      - ./scripts/mysql-connector-j-9.2.0.jar:/opt/bitnami/spark/scripts/mysql-connector-j-9.2.0.jar
      - ./spark-logs:/opt/bitnami/spark/spark-events
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    command: sbin/start-worker.sh spark://spark-master:7077
    depends_on:
      - "spark-master"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    command: sbin/start-worker.sh spark://spark-master:7077
    depends_on:
      - "spark-master"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-history:
    image: bitnami/spark:latest
    container_name: spark-history
    command: sbin/start-history-server.sh
    volumes:
      - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark-logs:/opt/bitnami/spark/spark-events
      - ./warehouse:/opt/bitnami/spark/warehouse
    ports:
      - "18080:18080"